# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Project/u200/project_dna_darrick/project_dna_darrick.runs/synth_1/.Xil/Vivado-18976-Laptop-Acer/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xcu200-fsgd2104-2-e
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    c:/Project/u200/project_dna_darrick/project_dna_darrick.srcs/sources_1/bd/design_1/ipshared/54bd/hdl/verilog
    c:/Project/u200/project_dna_darrick/project_dna_darrick.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_3/ip_0/source
    c:/Project/u200/project_dna_darrick/project_dna_darrick.srcs/sources_1/bd/design_1/ipshared/ec67/hdl
  } {
      C:/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      C:/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      C:/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    c:/Project/u200/project_dna_darrick/project_dna_darrick.srcs/sources_1/bd/design_1/ipshared/54bd/hdl/verilog
    c:/Project/u200/project_dna_darrick/project_dna_darrick.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_3/ip_0/source
    c:/Project/u200/project_dna_darrick/project_dna_darrick.srcs/sources_1/bd/design_1/ipshared/ec67/hdl
  } {
      C:/Project/u200/project_dna_darrick/project_dna_darrick.runs/synth_1/.Xil/Vivado-18976-Laptop-Acer/realtime/design_1_xdma_0_3_stub.v
      C:/Project/u200/project_dna_darrick/project_dna_darrick.runs/synth_1/.Xil/Vivado-18976-Laptop-Acer/realtime/design_1_util_ds_buf_3_stub.v
      C:/Project/u200/project_dna_darrick/project_dna_darrick.runs/synth_1/.Xil/Vivado-18976-Laptop-Acer/realtime/design_1_AXI_DNA_0_0_stub.v
      C:/Project/u200/project_dna_darrick/project_dna_darrick.runs/synth_1/.Xil/Vivado-18976-Laptop-Acer/realtime/design_1_xbar_0_stub.v
      C:/Project/u200/project_dna_darrick/project_dna_darrick.runs/synth_1/.Xil/Vivado-18976-Laptop-Acer/realtime/design_1_auto_ds_0_stub.v
      C:/Project/u200/project_dna_darrick/project_dna_darrick.runs/synth_1/.Xil/Vivado-18976-Laptop-Acer/realtime/design_1_auto_pc_0_stub.v
      C:/Project/u200/project_dna_darrick/project_dna_darrick.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
      C:/Project/u200/project_dna_darrick/project_dna_darrick.srcs/sources_1/bd/design_1/synth/design_1.v
    }
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList C:/Project/u200/project_dna_darrick/project_dna_darrick.runs/synth_1/.Xil/Vivado-18976-Laptop-Acer/realtime/design_1_wrapper_synth.xdc
    rt::sdcChecksum
    set rt::top design_1_wrapper
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter combineLutsPostRebuildHierarchy false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter repFanoutThreshold 400
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter inferFsm true
    rt::set_parameter encodeFsm one_hot
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops false
    rt::set_parameter earlyMaximalSharing false
    rt::set_parameter srlDepthThreshold 5
    rt::set_parameter rstSrlDepthThreshold 6
# MODE: 
    rt::set_parameter webTalkPath {C:/Project/u200/project_dna_darrick/project_dna_darrick.cache/wt}
    rt::set_parameter enableSplitFlowPath "C:/Project/u200/project_dna_darrick/project_dna_darrick.runs/synth_1/.Xil/Vivado-18976-Laptop-Acer/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
